const canvas = document.getElementById("scene"), ctx = canvas.getContext("2d", { alpha: false }), input = document.getElementById("textInput");
let width, height, cx, cy, particles = [], currentText = "", particleCount = 12000;
const CONFIG = { color: "#008B8B", sizeBase: 1.5, ease: 0.08, friction: 0.92, sphereRadius: 0.35 };
class Particle { constructor() { this.init(); } init() { this.x = Math.random() * (window.innerWidth || 800); this.y = Math.random() * (window.innerHeight || 600); this.tx = this.x; this.ty = this.y; this.vx = 0; this.vy = 0; this.size = Math.random() * CONFIG.sizeBase + 0.5; } update() { this.vx += (this.tx - this.x) * CONFIG.ease; this.vy += (this.ty - this.y) * CONFIG.ease; this.vx *= CONFIG.friction; this.vy *= CONFIG.friction; this.x += this.vx; this.y += this.vy; } draw() { ctx.fillStyle = CONFIG.color; ctx.fillRect(this.x, this.y, this.size, this.size); } }
function resize() { const dpr = Math.min(window.devicePixelRatio || 1, 2); width = window.innerWidth; height = window.innerHeight; canvas.width = width * dpr; canvas.height = height * dpr; canvas.style.width = width + "px"; canvas.style.height = height + "px"; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); cx = width / 2; cy = height / 2; particleCount = width < 600 ? 6000 : (width < 1200 ? 9000 : 14000); if (particles.length !== particleCount) initParticles(); updateTargets(); }
function initParticles() { particles = []; for (let i = 0; i < particleCount; i++) particles.push(new Particle()); }
function setSphereTargets() { const radius = Math.min(width, height) * CONFIG.sphereRadius; particles.forEach((p, i) => { const phi = Math.acos(-1 + (2 * i) / particles.length); const theta = Math.sqrt(particles.length * Math.PI) * phi; p.tx = cx + radius * Math.cos(theta) * Math.sin(phi); p.ty = cy + radius * Math.sin(theta) * Math.sin(phi); }); }
function setTextTargets(text) { const offCanvas = document.createElement("canvas"), offCtx = offCanvas.getContext("2d"); offCanvas.width = width; offCanvas.height = height; let fontSize = Math.min(width / (text.length * 0.5), height * 0.4); fontSize = Math.max(Math.min(fontSize, 180), 30); offCtx.font = `bold ${fontSize}px Inter, sans-serif`; offCtx.textAlign = "center"; offCtx.textBaseline = "middle"; offCtx.fillStyle = "white"; const words = text.split(" "); if (words.length > 3 && text.length > 15) { const mid = Math.floor(words.length / 2); offCtx.fillText(words.slice(0, mid).join(" "), cx, cy - fontSize * 0.6); offCtx.fillText(words.slice(mid).join(" "), cx, cy + fontSize * 0.6); } else offCtx.fillText(text, cx, cy); const data = offCtx.getImageData(0, 0, width, height).data, points = [], step = Math.max(1, Math.floor(Math.sqrt((width * height) / particles.length * 1.2))); for (let y = 0; y < height; y += step) for (let x = 0; x < width; x += step) if (data[(y * width + x) * 4 + 3] > 128) points.push({ x, y }); particles.forEach((p, i) => { const target = points[i % points.length] || { x: cx, y: cy }; p.tx = target.x; p.ty = target.y; }); }
function updateTargets() { const val = input.value.trim(); if (val) setTextTargets(val); else setSphereTargets(); }
input.addEventListener("input", updateTargets); window.addEventListener("resize", resize);
function animate() { ctx.fillStyle = "#000"; ctx.fillRect(0, 0, width, height); particles.forEach(p => { p.update(); p.draw(); }); requestAnimationFrame(animate); }
resize(); animate();
